# Generated by Django 4.2.11 on 2024-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_invoices', '0004_date_banking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='company_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company identification number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT identification number'),
        ),
    ]
