# Generated by Django 5.2.10 on 2026-01-27 11:59

import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_invoices', '0005_legalentity_company_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentityaddress',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
